package fr.imie.malah.designpattern.view;

import javax.swing.*;
import java.awt.*;

public class ButtonWorldView implements NextView {
    private JPanel panel;
    private JButton btnHelloWorld;
    private JButton btnExit;
    private JButton btnEmptyWorld;
    private JButton btnNext;

    public JButton getBtnHelloWorld() {
        return btnHelloWorld;
    }

    public JButton getBtnExit() {
        return btnExit;
    }

    public JButton getBtnEmptyWorld() {
        return btnEmptyWorld;
    }

    @Override
    public JButton getBtnNext() {
        return btnNext;
    }

    @Override
    public JPanel getPanel() {
        return panel;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel = new JPanel();
        panel.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        btnExit = new JButton();
        btnExit.setText("Exit");
        panel.add(btnExit);
        btnHelloWorld = new JButton();
        btnHelloWorld.setText("HelloWorld");
        panel.add(btnHelloWorld);
        btnEmptyWorld = new JButton();
        btnEmptyWorld.setText("EmptyWorld");
        panel.add(btnEmptyWorld);
        btnNext = new JButton();
        btnNext.setText("Next");
        panel.add(btnNext);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel;
    }
}
