package fr.imie.malah.designpattern.view;

import javax.swing.*;
import java.awt.*;

public class EmptyWorldView implements View {
    private JButton btnReturn;
    private JPanel panel;
    private JLabel lblEmptyWorld;

    public JButton getBtnReturn() {
        return btnReturn;
    }

    @Override
    public JPanel getPanel() {
        return panel;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel = new JPanel();
        panel.setLayout(new BorderLayout(0, 0));
        btnReturn = new JButton();
        btnReturn.setText("Return");
        panel.add(btnReturn, BorderLayout.SOUTH);
        lblEmptyWorld = new JLabel();
        lblEmptyWorld.setText("EmptyWorld");
        panel.add(lblEmptyWorld, BorderLayout.CENTER);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel;
    }


}
