package fr.imie.malah.designpattern.view;

import javax.swing.*;
import java.awt.*;

public class HelloWorldView implements NextView {
    private JPanel panel;
    private JLabel lblHelloWorld;
    private JButton btnReturn;
    private JButton btnEmptyWorld;
    private JButton btnNextView;

    public JButton getBtnReturn() {
        return btnReturn;
    }

    public JButton getBtnEmptyWorld() {
        return btnEmptyWorld;
    }

    @Override
    public JButton getBtnNext() {
        return btnNextView;
    }

    @Override
    public JPanel getPanel() {
        return panel;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel = new JPanel();
        panel.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        lblHelloWorld = new JLabel();
        lblHelloWorld.setText("HelloWorld");
        panel.add(lblHelloWorld);
        btnReturn = new JButton();
        btnReturn.setText("Return");
        panel.add(btnReturn);
        btnEmptyWorld = new JButton();
        btnEmptyWorld.setText("EmptyWorld");
        panel.add(btnEmptyWorld);
        btnNextView = new JButton();
        btnNextView.setText("Next");
        panel.add(btnNextView);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel;
    }
}
