-- TP 2
DROP DATABASE IF EXISTS tp2;
CREATE DATABASE IF NOT EXISTS tp2;

USE tp2;

CREATE TABLE IF NOT EXISTS client (
	id BIGINT AUTO_INCREMENT,
	nom VARCHAR(120) NOT NULL,
	PRIMARY KEY(id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS facture (
	id BIGINT AUTO_INCREMENT,
	date_facture DATETIME NOT NULL,
	client_id BIGINT NOT NULL,
	magasin_id BIGINT NOT NULL,
	PRIMARY KEY(id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS animal (
	id BIGINT AUTO_INCREMENT,
	prix DECIMAL(10,2) NULL,
	motif_prix VARCHAR(255) NULL,
	reference VARCHAR(10) NULL,
	magasin_id BIGINT NOT NULL,
	espece_id BIGINT NOT NULL,
	facture_id BIGINT NULL,
	PRIMARY KEY(id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS magasin (
	id BIGINT AUTO_INCREMENT,
	nom VARCHAR(120) NOT NULL,
	PRIMARY KEY(id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS espece (
	id BIGINT AUTO_INCREMENT,
	nom VARCHAR(120) NOT NULL,
	PRIMARY KEY(id)
) ENGINE=InnoDB;

ALTER TABLE facture ADD CONSTRAINT FK_facture_magasin
FOREIGN KEY (magasin_id) REFERENCES magasin(id);

ALTER TABLE facture ADD CONSTRAINT FK_facture_client
FOREIGN KEY (client_id) REFERENCES client(id);

ALTER TABLE animal ADD CONSTRAINT FK_animal_magasin
FOREIGN KEY (magasin_id) REFERENCES magasin(id);

ALTER TABLE animal ADD CONSTRAINT FK_animal_espece
FOREIGN KEY (espece_id) REFERENCES espece(id);

ALTER TABLE animal ADD CONSTRAINT FK_animal_facture
FOREIGN KEY (facture_id) REFERENCES facture(id);